### ISSUE TITLE
THE ILLUMINATI CONSPIRACY

### ISSUE THREAD

**Issue by DFXLuna** [DFXLuna/mazeGame#17]
Howdy all. By now you've probably seen the feedback we got on Program 2. The bad news is that we got a 60, the good news is that our code works on a windows box. This means our code doesn't work on linux.

The weird part is that, if the code is compiled on Linux but then run on Windows, the code works. so it's not a compilation problem. Dr. Ward said this means it's probably a memory issue happening at run time. Dr. Buckner said it would be wise to go through our code and see if there's something generating a bunch of extra objects.

What you need to do
-  Briefly go over your code and see if anything sticks out.
-  Remove stuff that we've not using and have commented out. This is unrelated to problem at hand but it needs to get done.

I'll be checking out the code in depth on Thursday to see if I can find the problem. Lemme know if ya'll find anything.

**Comment by MDFL64** [comment]
I was able to replicate the issue on Windows, but not very consistently.

I can't be sure, but I strongly suspect this is caused by the paint method's initial call running before everything is initialized. It seems that the first call to paint can be at any time after setVisible has been called. If this is the issue, minimizing and maximizing the window _might_ force a repaint (it does on Windows, no clue about Linux). To actually fix this we can initialize the UI after initializing the tile holders, or just call repaint ourselves once all the initialization is done, just to be safe.

I doubt there's any issues with memory. We would have to be doing something really absurd for there to be, and even then, it makes no sense that an issue with memory or the GC would be causing this kind of thing.

**Comment by DFXLuna** [comment]
So I can't actually replicate the issue on my own linux install using Eclipse and JDK8u77. I tried both before and after the backend update. I'm just gonna leave it for now and talk to Buckner on Friday.

**Comment by State307** [comment]
lmfao @DFXLuna

**Comment by jaredf1** [comment]
They dont want you to win

**Comment by MDFL64** [comment]
nice 1

I'd hoped that the lines could be scaled to 80-ish, if only for the sake of my stupid laptop screen, but re-adjusting it for 100 shouldn't be too hard.

Knowing our luck the problem is dependant on whatever window manager/kernel version/desktop environment/kernel version he has.

**Comment by DFXLuna** [comment]
Buckner said not to worry about it. So, for now, the Illuminati wins.
